
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  GCC:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install build infrastructure
        run: sudo apt-get install -y build-essential cmake ninja-build gcc-13 g++-13 libstdc++-13-dev

      - name: Build test
        run: |
          mkdir -p build/test 
          cd build/test
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQRCODE_TESTS_ENABLED:BOOL=True ../../
          ninja

      - name: Run test
        run: build/test/test/libqrcode_test

      - name: Build demo
        run: | 
          mkdir -p build/demo
          cd build/demo 
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLIBQRCODE_INCLUDE_DIR=$GITHUB_WORKSPACE/include/ ../../demo 
          ninja

      - name: Run demo
        run: |
          build/demo/demo "Hello World!" >> result.svg
          diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines demo/qrcode.svg result.svg

  Clang:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install build infrastructure
        run: sudo apt-get install -y build-essential cmake ninja-build clang-15 libstdc++-13-dev

      - name: Build test
        run: |
          mkdir -p build/test 
          cd build/test
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQRCODE_TESTS_ENABLED:BOOL=True ../../
          ninja

      - name: Run test
        run: build/test/test/libqrcode_test

      - name: Build demo
        run: | 
          mkdir -p build/demo
          cd build/demo 
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLIBQRCODE_INCLUDE_DIR=$GITHUB_WORKSPACE/include/ ../../demo 
          ninja

      - name: Run demo
        run: |
          build/demo/demo "Hello World!" >> result.svg
          diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines demo/qrcode.svg result.svg

  AppleClang:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build test
        run: |
          mkdir -p build/test 
          cd build/test
          cmake -GXcode -DQRCODE_TESTS_ENABLED:BOOL=True ../../
          xcodebuild -scheme ALL_BUILD -configuration Release build

      - name: Run test
        run: build/test/test/Release/libqrcode_test

      - name: Build demo
        run: | 
          mkdir -p build/demo
          cd build/demo 
          cmake -GXcode -DLIBQRCODE_INCLUDE_DIR=$GITHUB_WORKSPACE/include/ ../../demo 
          xcodebuild -scheme ALL_BUILD -configuration Release build

      - name: Run demo
        run: |
          build/demo/Release/demo "Hello World!" >> result.svg
          diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines demo/qrcode.svg result.svg

  MSVC:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build test
        shell: cmd 
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && mkdir build/test && cd build/test && cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQRCODE_TESTS_ENABLED:BOOL=True ../../ && ninja' }}

      - name: Run test
        run: build/test/test/libqrcode_test

      - name: Build demo
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && mkdir build/demo && cd build/demo && cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../../demo && ninja' }}

      - name: Run test
        shell: cmd 
        run: |
          build/demo/demo "Hello World!" >> result.svg
          diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines demo/qrcode.svg result.svg

