
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci_on_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install build infrastructure
        run: sudo apt-get install -y build-essential cmake ninja-build gcc-13 g++-13 libstdc++-13-dev

      - name: Build
        run: mkdir build && cd build && cmake -GNinja -DQRCODE_TESTS_ENABLED:BOOL=True ../ && ninja

  ci_on_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build
        shell: cmd 
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && mkdir build && cd build && cmake -GNinja -DQRCODE_TESTS_ENABLED:BOOL=True ../ && ninja' }}
